name: deploy on update index.html

on:
  push:
    branches:
      - main
    paths:
      - '*.html'
  workflow_dispatch:

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Téléchargement des artefacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
          
      - name: Déploiement vers GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}