name: deploy on update index.html

on:
  push:
    branches:
      - main
    paths:
      - '*.html'
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        
      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Téléchargement des artefacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
          
      - name: Déploiement vers GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}